# Generated by Django 5.1 on 2025-11-07 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('descricao', models.TextField(blank=True)),
                ('responsavel', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('andamento', 'Em andamento'), ('concluido', 'Concluído')], default='novo', max_length=12)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
